["{{ trimPrefix (print .chezmoi.homeDir .chezmoi.pathSeparator) .xdg.config }}/delta/themes/catppuccin.gitconfig"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig"
  refreshPeriod = "168h"
