return {
    'nvim-treesitter/nvim-treesitter',
    name = 'treesitter',
    branch = 'main',
    lazy = true,
    build = ":TSUpdate",
    config = function()
        local treesitter = require("nvim-treesitter")

        treesitter.install {
                'asm',
                'astro',
                'bash',
                'c',
                'c_sharp',
                'cmake',
                'comment',
                'cpp',
                'css',
                'csv',
                'dart',
                'desktop',
                'diff',
                'disassembly',
                'editorconfig',
                'gdscript',
                'gdshader',
                'git_config',
                'git_rebase',
                'gitattributes',
                'gitcommit',
                'gitignore',
                'glsl',
                'godot_resource',
                'gpg',
                'hlsl',
                'html',
                'ini',
                'java',
                'javadoc',
                'javascript',
                'jsdoc',
                'json',
                'json5',
                'jsonc',
                'lua',
                'luadoc',
                'luau',
                'passwd',
                'powershell',
                'markdown',
                'markdown_inline',
                'python',
                'query',
                'regex',
                'rust',
                'ssh_config',
                'tmux',
                'toml',
                'tsx',
                'typescript',
                'vhs',
                'vim',
                'vimdoc',
                'vue',
                'xml',
                'yaml',
            }
    end,
}
